### ISSUE TITLE
Results of doctests should be tallied alongside ordinary unit tests

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#109]
Currently, test.py runs doctests from README.md.  However, the number of passed and failed tests is not tallied alongside the other unit tests, although they are printed to the terminal.

Maybe we should simply import these tests rather than running the file directly.  

@travs @slarson @mwatts15

**Comment by slarson** [comment]
@gsarma Is there a way to run the doctests as part of a TestSuite with the other tests?  Would this help to incorporate the tallies together?  [This answer](https://stackoverflow.com/questions/5681330/using-doctests-from-within-unittests) on StackOverflow seems to have a solution that could be started.

The value of being able to run the Readme.md that I like is that there is zero redundancy -- only the readme has to be updated in order to modify the tests -- this ensures that they are always in sync, and that Travis-CI will always complain if we ever break any of the examples.  In the movement validation hackathon we found this to be something that would be very helpful as examples were getting broken but people weren't realising it...

**Comment by gsarma** [comment]
I think there is- I will look into it along with the other changes that need to be make to restore being able to run tests individually again.

**Comment by gsarma** [comment]
@travs and I took one step forward on this.  The doctests are now properly integrated into a test suite.  However, the entire suite is still counted as a single success or failure.  It shouldn't be too difficult from here to get the tests to register individually, but it took some reading to figure out various subtleties with doctests.  We'll issue a pull request once we've fully resolved the problem.  

Here is the commit for the small change we made:
https://github.com/gsarma/PyOpenWorm/commit/97cec3384ada72e0542f766058233a0c815a5596

**Comment by slarson** [comment]
Niiice!!

**Comment by slarson** [comment]
@gsarma why don't you go ahead and pull request this much, as it is still an improvement?  Then we can have splitting the tests individually as an additional issue.

**Comment by gsarma** [comment]
Sure thing!
