### ISSUE TITLE
Distribute worm.db and related files as data files

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#129]
Rather than creating them on install, moving them around, and changing permissions, it would be a lot easier to just distribute the database files the way they are when they're fully generated.

This means adding them in `package_data` in `setup.py`, as per [this](https://pythonhosted.org/setuptools/setuptools.html#including-data-files).

It will add some weight to the download (<10mb) but this won't be a problem once #99 is fixed.

**Comment by slarson** [comment]
There is actually a rationale behind why it is this way.  By rebuilding the DB "from source" each time with a new version, we ensure that the DB doesn't get out of sync with the information that makes it up.  Otherwise someone could make a change to, say, `insert_worm.py`, but never see it reflected in the actual data.

In addition, we can be sure that we don't start inserting things into the binary DB file that don't come from somewhere in the source. The goal there is to be able to track who has inserted what into the DB and use the version control of GitHub to do this.  

Does that make sense?  This is an experiment in how to distribute data and track provenance in a distributed manner via GitHub; so feel free to offer suggestions to this.

**Comment by travs** [comment]
Ok, yeah that makes sense.
One motivating factor behind opening this issue was also the difficulty in finding the install location (`site-packages` or `dist-packages` if Ubuntu) of PyOpenWorm, and making sure that the database gets in there. This would be one way to fix that, but there are certainly others.
