### ISSUE TITLE
Gather evidence for synapses from updated connectome chart

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#168]
Use the new connectome spreadsheet to source our connectome, and use this as the evidence as well.

**Comment by travs** [comment]
Steven Cook is going to be updating his new version of the C. elegans connectome (in spreadsheet form) to designate NMJ over the next few days.

**Comment by travs** [comment]
According to the author, the new connectome spreadsheet being used [here](https://github.com/openworm/PyOpenWorm/blob/60d2321017dcf37e8001613706487404fcf56c16/OpenWormData/aux_data/herm_full_edgelist.csv) is different than the old format, in that:
 > edges are included only as pre / post synaptic cells and does not include send, receive, or send polyad information

This should not be a problem and will actually simplify some things.

**Comment by pgleeson** [comment]
Shouldn't this spreadsheet (& where it's come from etc.) be on the [data sources page](https://github.com/openworm/PyOpenWorm/blob/dev/docs/data_sources.rst)?

**Comment by slarson** [comment]
Once it is actually a data source (i.e. actually integrated), absolutely!
ᐧ

**Comment by ahrasheed** [comment]
@travs I have added a check for _neuronal connections only_ to your new connection upload function [here](https://github.com/openworm/PyOpenWorm/commit/f33b71b8ee86e78065ec3f26eda8be242281bc67). Let me know if you disagree.

**Comment by travs** [comment]
@ahrasheed Sorry, I didn't get a chance to work on adding a `synonyms` and `wbid` property tonight. I'll do this tomorrow, and we can keep the discussion going in the gitter chat!

Let me know if there are any sticking points on modifying the functions in `insert_worm.py` or adding the cell list :smile:

**Comment by ahrasheed** [comment]
@travs @slarson 

I have generated a [PR](https://github.com/openworm/PyOpenWorm/pull/252) to **dev** branch for updating [insert_worm.py](https://github.com/openworm/PyOpenWorm/blob/new_connectome/OpenWormData/scripts/insert_worm.py) to utilize latest data sources, i.e. [new connectome](https://github.com/openworm/PyOpenWorm/blob/new_connectome/OpenWormData/aux_data/herm_full_edgelist.csv) and [wormbase cell list](https://github.com/openworm/PyOpenWorm/blob/new_connectome/OpenWormData/aux_data/C.%20elegans%20Cell%20List%20-%20WormBase.csv).

The code is fairly commented, however if some part is ambiguous, please do let me know. 

Conflicts will have to be removed before merging. 

Some data integrity tests are failing on this branch because these tests are using old spreadsheet for comparison. Such tests will have to be updated.

**Comment by mwatts15** [comment]
@ahrasheed: After #252, the DataIntegrityTests are the only thing missing to close this ticket?

**Comment by mwatts15** [comment]
The new data causes failure in `test_correct_number_unique_neurons` and `test_correct_connections_number` due to the extra connections alluded to above. Unless there's a compelling reason for adding these connections to the "neuron_network", it's probably better to make new connections list which includes both the neuronal net and these additional connections, like a 'cell_connections' property, but directly on the Worm object.

**Comment by mwatts15** [comment]
The referenced data source has been added and the docs/data_sources.rst file at the latest revision references the source file and it's origin in a personal communication from S. Cook.

However, checking the Evidence, the data was not going into the database. Fix coming directly.

**Comment by mwatts15** [comment]
Okay, we can close this ticket now.
