### ISSUE TITLE
Remove stray dependencies from files

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#170]
Discussion with @travs:
When we re-factored the PyOpenWorm test suite to breakdown individuals tests into files, we included most dependencies just to be safe and to make sure the suite ran as expected.  Many of these dependencies might not be needed, so it seems worth it to prune them away for future readability. 

@travs says there are automated tools to help with this process (SnakeFood).

**Comment by gsarma** [comment]
I got snakefood working and was able to generate a basic dependency graph.  I will probably need to go through all of the files manually and prune away the stray imports.  I'm not quite sure how snakefood generates these graph, so I might be misunderstanding exactly what the output is.

**Comment by gsarma** [comment]
It looks like snakefood doesn't do what I thought it was doing.  The dependency graphs are inferred from import statements, not by running the code and looking at which modules are actually imported.  Unfortunately, this is not so useful to us at the moment, but is a nice tool to know about.

**Comment by travs** [comment]
@gsarma I think this may still serve a useful purpose! There are kind of two issues here: one is finding dependencies that are installed in setup.py but never used in the rest of the code; The other is finding import statements that pull in code that is never used.

For the first one, if you use the `--follow` option in `sfood`, apparently, it follows the sub-dependencies of each direct dependency, so it should give us a full graph, even if it accesses these statically by import statements.

If we can just get a list of all dependencies imported in the project, we can find the unnecessary dependencies in `setup.py` quite easily. 

Unfortunately, I haven't gotten this to work yet (maybe because my venv has all kinds of unnecessary stuff in it). 

And as for the second issue of finding stray imports, I think you are right. There may be other tools to help with this though.
Quickly searching leads me to [gluttony](https://pypi.python.org/pypi/Gluttony/0.8) and [this other package](https://pypi.python.org/pypi/modulegraph/).

**Comment by travs** [comment]
Ooh, it looks like [pylint](http://www.pylint.org/) may actually do the second thing as well!

**Comment by gsarma** [comment]
@travs, yes the approach you described will definitely help us find stray dependencies in setup.py.  That's a great idea. 

But we still need a way to find stray dependencies in each of the testing files- it does look like pylint will take care of that.  We need to get a linter setup anyway, so maybe this is a good reason to get this started.

**Comment by gsarma** [comment]
@mwatts15 thanks! can you explain how you went about this?  @travs and I were looking into some static analysis tools some time ago but never came back to it.
