### ISSUE TITLE
Make net.neurons() return Neuron objects instead of strings

### ISSUE THREAD

**Issue by travs** [openworm/PyOpenWorm#178]
Raised from [here](https://github.com/openworm/PyOpenWorm/issues/158#issuecomment-118404848).

@slarson says:
> This could be improved, but at the moment, that is the [behavior in the api](https://pyopenworm.readthedocs.org/en/latest/_modules/PyOpenWorm/network.html#Network.neurons).  Superior behavior would be to return the objects instead of strings as now, but to make sure to implement [`__str__`, `__repr__` and maybe even `unicode`](http://stackoverflow.com/a/1535336/2733572) to ensure that the user can see a meaningful representation of the object when it is inspected interactively or printed out.

**Comment by travs** [comment]
Do #228 when this one is done.

**Comment by travs** [comment]
@signija Would you be interested in trying to fix this one? It is related to the test you wrote in #226

**Comment by signija** [comment]
Yeah, definitely! Just finished with #201 so I'll get started on this.

**Comment by travs** [comment]
@signija Sweet! Let me know if you run into any roadblocks!

**Comment by signija** [comment]
@travs What I've done so far is replace the code for net.neurons() so that it returns Neuron objects. This broke some other things (doctests and a NetworkTest, written with string return value in mind). In order to fix it, I tried writing another function net.neuronslist() that basically has the code of the previous function, so that we could use either one, depending on what we need. And here is where I ran into some problems.

What happens is, for a set of net.neuronslist(), length is 302, and sorted() returns the correct result. If I use list(net.neuronslist()), it's actually returning each string twice (so the list's length is 604).

Trying to figure out why this is happening - the code is essentially the same as the previous net.neurons(), so it should have the same behaviour. Am I missing something very obvious, though?

(Alternatively, I could've tried to change the failing tests so that they take Neuron objects into consideration, not strings, but I'm thinking the current option of adding another function may be more useful in the long term.)

**Comment by mwatts15** [comment]
`Network.neuron()` will already return a sequence of Neuron objects. `Network.neurons()` was intended specifically to return neuron names, or at least to return something that showed all of the neuron names.

**Comment by signija** [comment]
As far as I can see from the issues that caused this one, this may have been a mistake based on the fact that the [API](https://pyopenworm.readthedocs.org/en/latest/api.html#PyOpenWorm.Network) is not very clear on this: `Network.neurons()` is supposed to "get the complete set of neurons in this network"; so I'm assuming the documentation is the problem here as well.

Personally, I didn't realise I was actually doing the same thing as `Network.neuron()` (seems obvious now). I'm guessing mostly because of its being an `ObjectProperty` instead of a straightforward function - this threw me off, and a search for `.neuron()` didn't return anything particularly helpful. This could probably be solved by at least adding a comment somewhere about its use so that no one runs into the same problems and loses sight of `Network.neuron()` again (as it seems to have happened in #158 ?).

**Comment by slarson** [comment]
@signija Yes Improving the API would be welcome here :) Everybody having a look and deciding if it is clear and adapting it to be so is greatly appreciated.

**Comment by mwatts15** [comment]
Yes, it should be better documented. Since `Property` objects aren't attached through assignment as is typical in Python, a "Pythonic" way to document them was not clear to me at design time. For now, adding something to the class documentation as in the `Evidence` class should be sufficient.

Adapting `Property` to use the [descriptor protocol](https://docs.python.org/2/howto/descriptor.html) would allow to do this:
```python
class Blah(DataObject):
    prop = ObjectProperty('prop')
    """ A property """
```
Which has the advantage that Python tools can understand that the docstring attaches to the property. Not all tools seem to agree on whether the docstring goes above or below the assignment though ([jedi](https://github.com/davidhalter/jedi) via [YouCompleteMe](http://valloric.github.io/YouCompleteMe/) seems to expect them before the assignment while sphinx expects them after.

**Comment by travs** [comment]
Ok, the descriptor protocol looks interesting.
I think we can agree that `neuron` and `neurons` are too similarly named to have different behaviours. It seems reasonable to change the name of the function `neurons`, which returns neuron names, to be `neuron_names`, `get_neuron_names`, or something similar.

I think that providing descriptions in the class docstring is clear enough as a practice, it's just the naming (`neurons` v `neuron`) that was confusing.

To close this quickly, I am proposing that we:
- [ ] rename what is currently `neurons` to something more clear
- [ ] update relevant tests to call that new function name instead
- [ ] update the [docstring for `Network` class](https://github.com/openworm/PyOpenWorm/blob/dev/PyOpenWorm/network.py#L7-L15) to be more clear
- [ ] alias `neurons` to return the same thing as the `neuron` function does now (actual `Neuron` objects), similar to the aliases in the [neuron class](https://github.com/openworm/PyOpenWorm/blob/dev/PyOpenWorm/neuron.py#L78-L80)

**Comment by travs** [comment]
Closed by  https://github.com/openworm/PyOpenWorm/pull/244
