### ISSUE TITLE
Add 10.1371/journal.pcbi.1005283

### ISSUE THREAD

**Issue by mwatts15** [openworm/PyOpenWorm#284]
Add neurotransmitter expression info to insert_worm.py and attach Evidence with the author, title, DOI (below) and one or more URLs. Any other info available for the Evidence is desired.

Machine readable data is attached to the document on the web and is available here: http://journals.plos.org/ploscompbiol/article/file?type=supplementary&id=info:doi/10.1371/journal.pcbi.1005283.s004
DOI: 10.1371/journal.pcbi.1005283

Child of #274
related to #293 (overlap in the data source)

**Comment by mwatts15** [comment]
Still needs an update to the data sources page.

**Comment by clbarnes** [comment]
I'm going to hold off on that until the data spreadsheet here https://docs.google.com/spreadsheets/d/1kCxOOKu1wAREa9VbBiWVVHh-GEC3kJk0A3YVEipPKcc/edit#gid=0 has been cloned and put in the openworm public folder so I can link to it there rather than my own copy.

Incidentally, I don't think I can label or self-assign issues.
