### ISSUE TITLE
Clean up ion channel data and make 'ingest' more maintainable

### ISSUE THREAD

**Issue by mwatts15** [openworm/PyOpenWorm#319]
Ion channel data was recently added to PyOpenWorm, but there are a few things that should be done to make the translation more maintainable considering that the source data is still subject to change, so that future imports are likely.

- Replace magic numbers for columns with descriptive names (e.g., what's special about 101 in the neurons - channels spreadsheet)
- Detect and drop 'n/a', 'None', '' and similar for channel descriptions and expression patterns -- absence indicates lack of data in PyOpenWorm, so the n/a is superfluous
- It looks like the neuron - channels relationships can be between neurons or classes of neurons in the data set, but we distinguish between these in PyOpenWorm. Code should be added to detect when a column is a neuron class (i.e., create a list of which columns are neuron classes and check against that) and only create Neurons.
- Normalize the expression pattern data: it looks like there's some '|'-separated data in the expression_pattern column. It's not necessary now to make the effort of defining an expression pattern type, but at least the multiple entities embedded in that text should be broken out.

Data
1. [Neurons to channels](https://github.com/openworm/PyOpenWorm/blob/dev/OpenWormData/aux_data/Ion%20channels%20-%20Ion%20Channel%20To%20Body%20Muscle.tsv)
2. [Muscles to channels](https://github.com/openworm/PyOpenWorm/blob/dev/OpenWormData/aux_data/Ion%20channels%20-%20Ion%20Channel%20To%20Neuron.tsv)
3. https://github.com/openworm/PyOpenWorm/blob/dev/OpenWormData/aux_data/ion_channel.csv

**Comment by slarson** [comment]
Great stuff!  One note, we can drop the 'classes of neurons' info out because the columns that specify ion channel to neuron relationships build on the 'classes of neurons' data and therefore having them both is redundant.

On the modifying the TSV-- for the simplicity of the data sources page, can we keep the TSVs to be raw dumps from google spreadsheets and handle skipping headers in the code?  I get what you are saying about cleaner code, but we get better reproducibility here if there isn't an extra step to modify the TSV after it comes right out of our spreadsheet.

Thanks!!

**Comment by slarson** [comment]
@mwatts15 Did this ever get done in the course of GSoC / PRs by @shubhsingh594 ?

**Comment by mwatts15** [comment]
@slarson No, things are as they were.
