### ISSUE TITLE
Organize tests into folders by type

### ISSUE THREAD

**Issue by gsarma** [openworm/PyOpenWorm#326]
This is completely trivial and is pure housekeeping, but considering how many tests there are, we should probably separate them into different folders by functionality / test type.  I thought about this while browsing the repo for [Hail](https://github.com/hail-is/hail/tree/master/src/test/scala/is/hail), which is very well organized.  

Just in the spirit of making the codebase more transparent for newcomers.  

@mwatts15 we could probably do this in 15 min over the phone at some point. 

@slarson @rgerkin

**Comment by rgerkin** [comment]
Each of the test classes (which is generally its own file), already contains within it several actual unit tests (the class methods).  So the test class is doing the organization here, organizing by test type, e.g. all DataIntegrity tests are in one class.  And then there is homology between class and file.  So really it's a question of whether it is better to have a third layer of organization.  Technically we can even have 4 (directory, file, class, test).  

However, I actually think two is pretty reasonable.  What I might instead propose is to put multiple classes into the same file, for example all `Data*` classes can be in a `DataTests.py` file, and then the division into classes and then tests is evident within the file.  This also has the benefit of allowing someone to run all the DataTests with e.g. `python -m unittest DataTests`.  This might be useful if someone makes local changes that are unlikely to affect things other than the data tests, in which case they can run that command before committing and that let Travis do the boring job of running all the other test which are unlikely to have a change in status.  

Or we can just add files like `DataTests.py` that import all the other `Data*.py` files.  However, this leads to even more files than before.  I'm not a huge fan of directories though because of the challenge of doing relative imports in directories that the current file is not in.  This can be a problem when tests share code, in which case that code has to be refactored to be in some higher level module.

**Comment by mwatts15** [comment]
Thanks, @gsarma @rgerkin. The tests don't need a deeper hierarchy at this point. If anything is to be added it would be preferable to add markers, which can cut across methods and test cases. It's possible to select tests that are 'marked' by using the -m option to py.test.

@rgerkin although the tests use unittest names, they are accessed through the py.test wrapper.
