### ISSUE TITLE
Should synclass() in Connection return neurotransmitter info?

### ISSUE THREAD

**Issue by pgleeson** [openworm/PyOpenWorm#401]
It seems like synclass() here: https://github.com/openworm/PyOpenWorm/blob/c46def3023f1f0946873267883c0351066038711/PyOpenWorm/connection.py#L38 should return the neurotransmitter, e.g. see https://github.com/openworm/PyOpenWorm/blob/c46def3023f1f0946873267883c0351066038711/examples/NetworkInfo.py#L55, but it returns None. 

Output of https://github.com/openworm/c302/blob/feature/update-openworm-reader-10/c302/OpenWormReader.py should have info on neurotransmitter (the fact thta the connections are missing is a different issue):
```
...
c302      >>>  Missing from UpdatedSpreadsheetDataReader: Connection from VM2PR to VC3 (2 times, type: GapJunction, neurotransmitter: None)
c302      >>>  Missing from UpdatedSpreadsheetDataReader: Connection from PM4DR to I3 (3 times, type: GapJunction, neurotransmitter: None)
c302      >>>  Missing from UpdatedSpreadsheetDataReader: Connection from PM5VL to M5 (2 times, type: GapJunction, neurotransmitter: None)
c302      >>>  Missing from UpdatedSpreadsheetDataReader: Connection from PM5DL to M2R (1 times, type: GapJunction, neurotransmitter: None)

...
```

**Comment by mwatts15** [comment]
Yes, the data source the connections are created from in this case don't populate the `synclass`.

**Comment by pgleeson** [comment]
Thanks for checking. That will most likely be needed so OpenWormReader can pass the correct info on synapse types to c302.

**Comment by mwatts15** [comment]
I've added the "synclass" entries from the Shterionov (2011) data that we had been using to the [openworm/OpenWormData](https://github.com/openworm/OpenWormData) repo, but found that there's a pretty big mismatch between that and the data from wormwiring.org that we're using now.

I've created a separate ticket, #419, to address the gap since I think this issue is answered by the inclusion of *some* neurotransmitters.
